from enum import Enum

class MachineState(str, Enum):
    NORMAL = "NORMAL"
    WARNING = "WARNING"
    DEGRADING = "DEGRADING"
    CRITICAL = "CRITICAL"
    FAILURE = "FAILURE"

class FailureMode(str, Enum):
    NORMAL_OPERATION = "NORMAL_OPERATION"
    BEARING_FAILURE = "BEARING_FAILURE"
    OVERHEATING = "OVERHEATING"
    ELECTRICAL_FAULT = "ELECTRICAL_FAULT"
    IMBALANCE = "IMBALANCE"
